# Generated by Django 3.1.1 on 2020-09-02 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='name',
            field=models.CharField(default='test', max_length=80),
        ),
    ]
